name: ci

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn render
      - uses: actions-js/push@master
        with:
          directory: "./docs"
          message: "bot: autopublish"
          github_token: ${{ secrets.GITHUB_TOKEN }}
